server:
  port: 8080
  
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: JODConverter Sample Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages
  
logging:
  level:
    org.jodconverter: debug
